"""Privacy/kind rules shared by build_insights.py and the ingest trial (stdlib only).

Anything matching here is kept out of every derived output; the catalog's own 'personal'
label misses statements, invoices, tickets, CVs and NDAs. Re-audit outputs after any change.
"""
import re

# Personal-document guard: the catalog's 'personal' label misses many statements/forms.
SENSITIVE_DOC = re.compile(
    r"\b[A-Z]{5}\d{4}[A-Z]\b|\b\d{4}\s\d{4}\s\d{4}\b|account statement|bank statement|"
    r"\bIFSC\b|account (?:no|number)|passport (?:no|number)|salary slip|payslip|form[ -]?16\b|"
    r"date of birth|permanent account number|folio no|policy number|e-?ticket|boarding pass|\bPNR\b|"
    r"tax invoice|invoice (?:no|number)|order (?:id|no)\b|booking (?:id|ref)", re.I)
SENSITIVE_DOC = re.compile(SENSITIVE_DOC.pattern + r"|client ledger|ledger statement|contract note|\bdemat\b|"
                           r"tax declaration|curriculum vitae|\bCV\b|résumé|\bresume\b|client id|nominee|form ?26as|"
                           r"annexure|\bstmt\b|capital gains? statement|holding statement", re.I)
# Title-only terms: too generic to match inside body text, but decisive in a filename.
SENSITIVE_TITLE = re.compile(
    r"gpay|phonepe|paytm|hall ticket|admit card|ticket confirmation|invoice|receipt|passport|(?<![a-z])nda(?![a-z])|agreement|"
    r"(?:credit[ _-]?card|\bcc|account|bank|quarterly|monthly|personal|salary)[ _-]*(?:financial[ _-]*)?statement|"
    r"statement[ _-]*(?:of[ _-]*)?(?:account|transactions)|financial statement certificate|certificate|"
    r"\bvisa\b|\bpan[ _-]?card|aadhaar|offer letter|payslip|itr[ _-]?v?\b|"
    r"umashankar|dwarakanathan|cover[ _-]?letter|\bcv\b|r[ée]sum[ée]|ticket|reco[ _-]?\d?\b", re.I)
NAME_DOC = re.compile(r"umashankar|dwarakanathan", re.I)
OWN_TEXT = re.compile(r"masaladeutsch|herrrickshaw|market-pipeline|bazaartalks|piotroski|darvas|bullcartel|"
                      r"generated by claude|daily scan report", re.I)
PRIVATE_FOLDERS = {"cv", "Documents", "Attachments", "all unorganised files"}  # never surface titles from these
# The pipeline's own products and machine backups are not literature: keep them out of the
# corpus statistics, and report them separately as "what you write".
OWN_PATH = re.compile(r"home-backup|umashankar[_-]mac|\.graphify|gh-clones|blogger_writeups|market-data-|"
                      r"market-pipeline|research_md_corpus|laptop_backup|Machine_Backup|Mein PC|My Mac", re.I)


def is_sensitive(title, head, kind="literature"):
    """True if a document must be dropped from all derived outputs."""
    t = title or ""
    text = t + " " + (head or "")[:3000]
    return bool(SENSITIVE_DOC.search(text) or SENSITIVE_TITLE.search(t)
                or (kind == "literature" and NAME_DOC.search(text)))
